/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { RegionalStats, Supplier, NewsArticle } from './types';

export const REGIONS: RegionalStats[] = [
  {
    id: 'scotland-north',
    name: 'Scotland North & Islands',
    spotPrice: 6.85,
    priceTrend: 'down',
    productionCapacity: 145,
    storageLevel: 82,
    pipelineStatus: 'Expanding',
    demandForecast: 90,
    carbonIntensity: 0.12,
  },
  {
    id: 'scotland-south',
    name: 'Scotland Central & South',
    spotPrice: 6.20,
    priceTrend: 'stable',
    productionCapacity: 210,
    storageLevel: 74,
    pipelineStatus: 'Operational',
    demandForecast: 185,
    carbonIntensity: 0.24,
  },
  {
    id: 'north-east',
    name: 'North East & Teesside',
    spotPrice: 4.25,
    priceTrend: 'down',
    productionCapacity: 480,
    storageLevel: 91,
    pipelineStatus: 'Nominal',
    demandForecast: 410,
    carbonIntensity: 0.98,
  },
  {
    id: 'north-west',
    name: 'North West & Mersey',
    spotPrice: 4.40,
    priceTrend: 'up',
    productionCapacity: 350,
    storageLevel: 68,
    pipelineStatus: 'Nominal',
    demandForecast: 380,
    carbonIntensity: 0.89,
  },
  {
    id: 'midlands',
    name: 'Midlands Transmission Zone',
    spotPrice: 5.15,
    priceTrend: 'up',
    productionCapacity: 80,
    storageLevel: 45,
    pipelineStatus: 'Maintenance',
    demandForecast: 190,
    carbonIntensity: 0.65,
  },
  {
    id: 'wales',
    name: 'Wales Industrial Cluster',
    spotPrice: 6.95,
    priceTrend: 'stable',
    productionCapacity: 110,
    storageLevel: 62,
    pipelineStatus: 'Nominal',
    demandForecast: 105,
    carbonIntensity: 0.19,
  },
  {
    id: 'east-anglia',
    name: 'East Anglia & Bacton',
    spotPrice: 5.80,
    priceTrend: 'down',
    productionCapacity: 160,
    storageLevel: 88,
    pipelineStatus: 'Operational',
    demandForecast: 120,
    carbonIntensity: 0.21,
  },
  {
    id: 'south-west',
    name: 'South West & Severn',
    spotPrice: 7.20,
    priceTrend: 'up',
    productionCapacity: 75,
    storageLevel: 51,
    pipelineStatus: 'Expanding',
    demandForecast: 95,
    carbonIntensity: 0.08,
  },
  {
    id: 'south-east',
    name: 'South East & London Hub',
    spotPrice: 5.95,
    priceTrend: 'stable',
    productionCapacity: 120,
    storageLevel: 58,
    pipelineStatus: 'Nominal',
    demandForecast: 240,
    carbonIntensity: 0.42,
  },
];

export const SUPPLIERS: Supplier[] = [
  {
    id: 'caledonian-green',
    name: 'Caledonian Green Hydrogen',
    type: 'Green',
    description: 'Pioneering electrolytic hydrogen generated from high-yield offshore wind farms in the North Sea and Shetland tide cascades.',
    location: 'Aberdeen & Orkney, Scotland',
    capacityTonnesDay: 125,
    regionsServed: ['scotland-north', 'scotland-south', 'north-east'],
    certifications: ['Renewable H2 Guarantee of Origin', 'DESNZ Low Carbon Hydrogen Standard', 'BSI 14001'],
    emissionIntensity: 0.12,
    pricingIndicative: 6.85,
    purityGrade: '99.999% Ultra-Pure (Grade D Fuel Cell ISO 14687)',
    deliveryOptions: ['Road Tanker (Liquid)', 'Tube Trailer (Gaseous)', 'Direct Pipeline Connection'],
    contactEmail: 'procurement@caledonian-h2.co.uk',
    contactPhone: '+44 (0) 1224 990422',
    overview: 'Caledonian Green Hydrogen operates the Flotta and Orkney electrolysis arrays, utilizing surplus offshore wind power. We are the prime contractor supplying heavy transport fleets and marine shipping pilot programs in northern Britain.',
    infrastructureProjects: ['Orkney Deep Water Terminal Pipeline', 'Aberdeen Heavy Bus Depot Pipeline Extension'],
    sustainabilityRating: 'AAA',
  },
  {
    id: 'teesside-netzero',
    name: 'Teesside NetZero Consortium',
    type: 'Blue',
    description: 'Bulk industrial reforming with world-class carbon capture and deep North Sea geological sequestration, built for heavy petrochemical manufacture.',
    location: 'Redcar, Teesside',
    capacityTonnesDay: 320,
    regionsServed: ['north-east', 'midlands', 'north-west', 'east-anglia'],
    certifications: ['DESNZ Certified Low Carbon', 'Carbon Capture Assurance Protocol', 'ISO 9001'],
    emissionIntensity: 0.98,
    pricingIndicative: 4.25,
    purityGrade: '99.97% Industrial Feedstock (Refinery & Chemical Grade)',
    deliveryOptions: ['Direct Pipeline Connection', 'Liquefied Train Tanker'],
    contactEmail: 'bulk@teesside-netzero.org.uk',
    contactPhone: '+44 (0) 1642 770800',
    overview: 'Teesside NetZero is Britain’s largest supplier of clean industrial hydrogen, leveraging advanced autothermal reforming (ATR) combined with a 97% effective carbon capture network. Our site feeds the main chemical corridor of Teesside directly.',
    infrastructureProjects: ['Northern Endurance Carbon Pipeline Project', 'East Coast Grid Backbone link'],
    sustainabilityRating: 'A',
  },
  {
    id: 'mersey-basin',
    name: 'Mersey Basin Hydrogen',
    type: 'Blue',
    description: 'HyNet project anchor producer, driving industrial decarbonisation across the North West and North Wales manufacturing corridor.',
    location: 'Ellesmere Port, Cheshire',
    capacityTonnesDay: 250,
    regionsServed: ['north-west', 'wales', 'midlands'],
    certifications: ['HyNet Low Carbon Seal', 'ISO 50001 Energy Management'],
    emissionIntensity: 0.89,
    pricingIndicative: 4.40,
    purityGrade: '99.95% Standard Industrial Grade',
    deliveryOptions: ['Direct Pipeline Connection', 'Tube Trailer (Gaseous)'],
    contactEmail: 'operations@mersey-h2.co.uk',
    contactPhone: '+44 (0) 151 496 0199',
    overview: 'Positioned at the heart of the North West industrial cluster, Mersey Basin Hydrogen provides low-cost, low-carbon hydrogen to glass, cement, and chemical facilities. We run integrated salt cavern storage integration for seasonal buffer loads.',
    infrastructureProjects: ['Cheshire Salt Cavern Storage Phase II', 'Stanlow Refinery Grid Injection Loop'],
    sustainabilityRating: 'A+',
  },
  {
    id: 'humber-clean',
    name: 'Humber Clean Energy Partners',
    type: 'Green',
    description: 'Gigawatt-scale green hydrogen electrolysis integrated with East Coast offshore wind nodes, supplying the Humber industrial heartland.',
    location: 'Grimsby & Immingham',
    capacityTonnesDay: 160,
    regionsServed: ['north-east', 'east-anglia', 'midlands'],
    certifications: ['Renewable Energy Certificate (REC)', 'TÜV Rheinland Green Hydrogen Standard'],
    emissionIntensity: 0.15,
    pricingIndicative: 6.95,
    purityGrade: '99.999% Ultra-Pure (Grade D Fuel Cell)',
    deliveryOptions: ['Road Tanker (Liquid)', 'Tube Trailer (Gaseous)'],
    contactEmail: 'supplies@humber-cleanenergy.co.uk',
    contactPhone: '+44 (0) 1472 881200',
    overview: 'A joint venture between offshore wind operators and international logistics hubs, Humber Clean Energy operates state-of-the-art PEM electrolysers at Immingham Port. Designed to scale to 1GW by 2030 to supply the regional maritime and industrial fleets.',
    infrastructureProjects: ['Immingham Shipping Refuelling Jetty', 'Bacton Interconnector Feeder'],
    sustainabilityRating: 'AA+',
  },
  {
    id: 'cambrian-consortium',
    name: 'Cambrian Hydrogen Consortium',
    type: 'Green',
    description: 'Deep-water port electrolytic hub optimizing onshore Welsh wind and marine tidal energy arrays for heavy logistics and steel manufacture.',
    location: 'Milford Haven, Pembrokeshire',
    capacityTonnesDay: 95,
    regionsServed: ['wales', 'south-west', 'midlands'],
    certifications: ['Welsh Green Energy Registry', 'BSI ISO 14001'],
    emissionIntensity: 0.18,
    pricingIndicative: 6.95,
    purityGrade: '99.99% High-Pure Logistics Grade',
    deliveryOptions: ['Tube Trailer (Gaseous)', 'Road Tanker (Liquid)', 'Coastal Feeder Ship'],
    contactEmail: 'b2b@cambrianhydrogen.wales',
    contactPhone: '+44 (0) 1646 554300',
    overview: 'Cambrian Hydrogen is built specifically to address the South Wales Industrial Cluster (SWIC) needs, prioritizing steelworks transition and coastal maritime transport. We operate custom marine bunker barges for coastal hydrogen transport.',
    infrastructureProjects: ['Port Talbot Steel Pipeline Link', 'Milford Haven Maritime Refuelling Dock'],
    sustainabilityRating: 'AA',
  },
  {
    id: 'sizewell-pink',
    name: 'Sizewell Pink H2',
    type: 'Pink',
    description: 'High-efficiency nuclear thermal-electrolysis using baseload power, providing exceptionally stable, zero-carbon hydrogen supply 24/7.',
    location: 'Sizewell, Suffolk',
    capacityTonnesDay: 150,
    regionsServed: ['east-anglia', 'south-east', 'midlands'],
    certifications: ['Nuclear Free-Emission Standard', 'DESNZ Low Carbon Standard', 'ISO 9001'],
    emissionIntensity: 0.22,
    pricingIndicative: 5.80,
    purityGrade: '99.999% Ultra-Pure (Fuel Cell Grade)',
    deliveryOptions: ['Tube Trailer (Gaseous)', 'Direct Pipeline Connection'],
    contactEmail: 'commercial@sizewell-pinkh2.co.uk',
    contactPhone: '+44 (0) 1728 665400',
    overview: 'Leveraging constant thermal and electrical outputs from nuclear baseload power, Sizewell Pink H2 operates high-temperature solid oxide electrolysers (SOEC). By utilizing secondary reactor heat, we achieve thermal-electrolysis efficiencies far exceeding cold wind electrolysis, offering rock-solid delivery contracts unaffected by weather variations.',
    infrastructureProjects: ['Suffolk transport corridor refueling spine', 'London East Gateway Injection Station'],
    sustainabilityRating: 'AA',
  },
  {
    id: 'wessex-wind',
    name: 'Wessex Wind-to-H2',
    type: 'Green',
    description: 'Bespoke floating wind and tidal stream integration along the Bristol Channel, serving transport corridors and aerospace testing centers.',
    location: 'Avonmouth, Bristol',
    capacityTonnesDay: 65,
    regionsServed: ['south-west', 'south-east', 'wales'],
    certifications: ['South West Energy Alliance Stamp', 'BSI 14064 Carbon Footprint Verified'],
    emissionIntensity: 0.08,
    pricingIndicative: 7.20,
    purityGrade: '99.9995% Research & Aerospace Grade (Extreme Purity)',
    deliveryOptions: ['Tube Trailer (Gaseous)', 'Specialty High-Pressure Gas Cylinders'],
    contactEmail: 'orders@wessex-wind-h2.co.uk',
    contactPhone: '+44 (0) 117 3349000',
    overview: 'Wessex Wind-to-H2 was established to serve the premium aerospace cluster of the South West. Our hydrogen is certified to extreme levels of purity, satisfying testing requirements for clean jet engines, aerospace composites, and fuel-cell aviation propulsion.',
    infrastructureProjects: ['Filton Aerospace Corridor Dedicated Feed', 'Bristol Port Heavy Transit Oasis'],
    sustainabilityRating: 'AAA',
  }
];

export const NEWS: NewsArticle[] = [
  {
    id: 'news-1',
    title: 'Department for Energy Security and Net Zero (DESNZ) Announces £2.5B Support for Northern Hydrogen Backbone',
    source: 'Financial Times',
    category: 'Regulation',
    timestamp: '2026-07-18T09:00:00Z',
    summary: 'The UK government has approved capital funding to fast-track the conversion of National Gas Transmission pipelines to carry 100% pure hydrogen, linking Teesside and Grangemouth chemical clusters.',
    readTime: '4 min read',
  },
  {
    id: 'news-2',
    title: 'Caledonian Green Hydrogen Achieves Record Electrolysis Yield at Flotta Offshore Wind Terminal',
    source: 'Hydrogen Grid Review',
    category: 'Technology',
    timestamp: '2026-07-17T14:30:00Z',
    summary: 'New Solid Oxide PEM hybrid systems installed in Orkney show a 14% improvement in electrical conversion efficiency, driving down northern spot prices.',
    readTime: '3 min read',
  },
  {
    id: 'news-3',
    title: 'Teesside Industrial Cluster Commences Hydrogen Pipeline Feeding to local Chemical Corridors',
    source: 'InfraBritain',
    category: 'Infrastructure',
    timestamp: '2026-07-15T11:15:00Z',
    summary: 'Direct pipeline deliveries have commenced for the Redcar industrial park, replacing traditional grey gas feedstock with 99.97% low-carbon blue hydrogen.',
    readTime: '5 min read',
  },
  {
    id: 'news-4',
    title: 'Hydrogen Spot Prices Soften Across UK Regions as Offshore Wind Surpluses Peak',
    source: 'Bloomberg Energy',
    category: 'Market',
    timestamp: '2026-07-14T16:00:00Z',
    summary: 'High winds across the North Sea have triggered widespread grid curtailment payments, resulting in record-low electricity input prices and a subsequent fall in green hydrogen tariffs.',
    readTime: '3 min read',
  }
];

export const PRICE_HISTORY = {
  months: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul'],
  green: [7.20, 7.10, 6.95, 6.85, 6.90, 6.75, 6.68],
  blue: [4.65, 4.55, 4.50, 4.45, 4.40, 4.35, 4.32],
  pink: [6.10, 6.00, 5.95, 5.90, 5.85, 5.80, 5.82],
};
